baseURL = "https://qiect.github.io/pcnav/"
languageCode = "zh-CN"
title = "ğŸ¬ä¸€é¢—è·³è·³ç³–"
theme = "PCNav"
preserveTaxonomyNames = true
disablePathToLower = true
hasCJKLanguage = true
publishDir = "docs"


[params]
    author        = "Chet"
    description   = "æˆ‘æ˜¯ä¸€ä¸ªç³–ï¼Œä¸€é¢—ä»€ä¹ˆç³–ï¼Ÿæˆ‘æ˜¯ä¸€é¢—æ´»åŠ›å››å°„ã€æœæ°”è“¬å‹ƒã€äº”å½©ç¼¤çº·çš„è·³è·³ç³–~"
    siteurl       = "./"
    about         = "https://msg.cnblogs.com/send/qiect"   # å·¦ä¾§å¯¼èˆªæ çš„"å…³äºå¯¼èˆª"é¡µé¢(./about)
    repository    = "https://github.com/qiect"
    enablePreLoad = true		    		        # ç½‘ç«™å®Œå…¨æ‰“å¼€å‰é¢„åŠ è½½çš„åŠ¨ç”»
    textPreLoad   = "ğŸ¬ä¸€é¢—è·³è·³ç³–"				# é¢„åŠ è½½çš„åŠ¨ç”»æ–‡å­—, åªæœ‰å½“enablePreLoad=trueæ—¶ç”Ÿæ•ˆ
    logosPath     = "assets/images/logos"				# ç½‘ç«™æ¯ä¸ªå¯¼èˆªåœ°å€logoå­˜æ”¾åœ°å€

[params.qweather]
    key = "085791e805a24491b43b06cf58ab31e7"

[params.images]
    favicon           = "assets/images/favicon.png"
    searchImageL      = ""		#æœç´¢éƒ¨åˆ†æµ…è‰²èƒŒæ™¯å›¾
    searchImageD      = ""		#æœç´¢éƒ¨åˆ†æ·±è‰²èƒŒæ™¯å›¾
    logoExpandLight   = "assets/images/bioitee-expand-light.png"
    logoExpandDark    = "assets/images/bioitee-expand-dark.png"
    logoCollapseLight = "assets/images/logo-collapse-light.png"
    logoCollapseDark  = "assets/images/logo-collapse-dark.png"
    
[markup.goldmark.renderer]
    unsafe = true

[params.footer]
    copyright = 'æœ¬ç«™å†…å®¹æºè‡ªäº’è”ç½‘ï¼Œå¦‚æœ‰å†…å®¹ä¾µçŠ¯äº†ä½ çš„æƒç›Šï¼Œè¯·è”ç³»åˆ é™¤ç›¸å…³å†…å®¹ï¼Œè”ç³»é‚®ç®±ï¼šqctvip@vip.163.com <br/>&copy; 2021 - {year} By [PCNAV](https://github.com/qiect/pcnav/)<br/>'
